### ISSUE TITLE
overleaf上的编译问题

### ISSUE THREAD

**Issue by YDream5** [Elitedj/Resume#1]
请问有尝试在overleaf上编译过吗，我下载对应的字体放在对应文件夹后在overleaf无法编译成功
![图片](https://github.com/Elitedj/Resume/assets/110643670/181164a1-e92b-4168-a27d-7672823827f0)
![图片](https://github.com/Elitedj/Resume/assets/110643670/3f03244e-816e-4ffa-b5f5-98a8bbd511d1)

**Comment by YDream5** [comment]
解决了，编译器选择的问题，要将默认的pdfLaTex改为XeLaTex，一开始以为是字体的问题换了好几种字体，谢谢佬

**Comment by Elitedj** [comment]
> 解决了，编译器选择的问题，要将默认的pdfLaTex改为XeLaTex，一开始以为是字体的问题换了好几种字体，谢谢佬

okk，祝求职顺利
